[package]
name = "ai"
version = "0.1.0"
authors = ["lytharn <lytharn@users.noreply.github.com>"]
edition = "2018"

[dependencies]
client = { path = "../client" }
rand = "0.7.3"

[dev-dependencies]
assert_matches = "1.3"